title: My first page
author: loglnlg2
email: some_email@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is my second course here, and I'm learning
  to do some things, don't know what I want the most
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  loglnlg2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
